Update add-pr-comment-command.yml

diff --git a/.github/workflows/add-pr-comment-command.yml b/.github/workflows/add-pr-comment-command.yml
--- a/.github/workflows/add-pr-comment-command.yml
+++ b/.github/workflows/add-pr-comment-command.yml
@@ -2,14 +2,29 @@ name: Add PR Comment
 
 on:
   repository_dispatch:
-    types: [add-pr-comment-command]  
-
+    types: [add-pr-comment-command]
+  pull_request:
+    types: [opened, synchronize, reopened]
+    
 jobs:
   add_comment:
     runs-on: ubuntu-latest
     # Do this only if the PR was created by dependabot
     if: github.event.client_payload.pull_request.user.login == 'dependabot[bot]'
     steps:
+      - name: Must be triggered by a command or is a PR created by Dependabot.
+        run: |
+          if [ 
+          
+          !(("${{ github.event_name }}" = "repository_dispatch" ] && [ "${{ github.event.action }}" = "add-pr-comment-command") 
+          ||
+          ("${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.user.login }}" = "dependabot[bot]"))
+          
+          ]; then
+            echo "Test criteria failed. Exiting..."
+            exit 1
+          fi
+      
       - name: Trigger the visual testing
         uses: peter-evans/create-or-update-comment@v2
         with:
@@ -17,4 +32,4 @@ jobs:
           repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
           issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
           body: |
-            /add-solo-comment
+            The test criteria passed.
